### ISSUE TITLE
Maintainence status

### ISSUE THREAD

**Issue by rgri** [rgri/tex2nix#29]
I see that you're looking for a new maintainer. I'm new to the OSS and Nix communities and am looking for the chance to gain some experience. Would this project be a good place to start? If so, I'm pretty familiar with latex having used it in school extensively, and I know how to read Nix and use Flakes.

**Comment by Mic92** [comment]
Sure. Do you want to have this project in your own account or nix-community?

**Comment by rgri** [comment]
I suppose I would prefer my own account.

**Comment by Mic92** [comment]
A request is out, you probably need to visit https://github.com/Mic92/tex2nix to see a popup?

**Comment by rgri** [comment]
Right, thanks. I was emailed and the transfer is in progress :+1:
